//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18047
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CubeIsland.LyricsReloaded.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CubeIsland.LyricsReloaded.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die name: &quot;azlyrics.com&quot;
        ///
        ///variables:
        ///    artist:
        ///        type: artist
        ///        filters:
        ///        - lowercase
        ///        - [strip_nonascii, &quot;&quot;]
        ///    title:
        ///        type: title
        ///        filters: artist
        ///
        ///config:
        ///    url: &quot;http://www.azlyrics.com/lyrics/{artist}/{title}.html&quot;
        ///    pattern: [&quot;&lt;!-- start of lyrics --&gt;(?&lt;lyrics&gt;.+?)&lt;!-- end of lyrics --&gt;&quot;, s]
        ///    
        ///post-filters:
        ///- strip_html
        ///- trim
        ///- utf8_encode ähnelt.
        /// </summary>
        public static string provider_azlyrics_com {
            get {
                return ResourceManager.GetString("provider_azlyrics_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] provider_cuspajz_com {
            get {
                object obj = ResourceManager.GetObject("provider_cuspajz_com", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die name: &quot;letras.mus.br&quot;
        ///
        ///variables:
        ///    artist:
        ///        type: artist
        ///        filters:
        ///        - lowercase
        ///        - [strip_nonascii, -]
        ///    title:
        ///        type: title
        ///        filters: artist
        ///
        ///config:
        ///    url: &quot;http://letras.mus.br/{artist}/{title}/&quot;
        ///    pattern: [&quot;&lt;div id=&quot;div_letra&quot;[^&gt;]*&gt;(?&lt;lyrics&gt;.*?)&lt;/div&gt;&quot;, s]
        ///    
        ///post-filters:
        ///- p2break
        ///- strip_html
        ///- clean_spaces
        ///- utf8_encode ähnelt.
        /// </summary>
        public static string provider_letras_mus_br {
            get {
                return ResourceManager.GetString("provider_letras_mus_br", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die name: &quot;metrolyrics.com&quot;
        ///
        ///variables:
        ///    artist:
        ///        type: artist
        ///        filters:
        ///        - lowercase
        ///        - [strip_nonascii, -]
        ///    title:
        ///        type: title
        ///        filters: artist
        ///
        ///config:
        ///    url: &quot;http://www.metrolyrics.com/{title}-lyrics-{artist}.html&quot;
        ///    pattern: [&quot;&lt;div id=\&quot;lyrics-body\&quot;&gt;(?&lt;lyrics&gt;.*?)&lt;/div&gt;&quot;, s]
        ///    
        ///post-filters:
        ///- strip_html
        ///- strip_links
        ///- entity_decode
        ///- clean_spaces
        ///- utf8_encode ähnelt.
        /// </summary>
        public static string provider_metrolyrics_com {
            get {
                return ResourceManager.GetString("provider_metrolyrics_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die name: &quot;oldielyrics.com&quot;
        ///
        ///variables:
        ///    artist:
        ///        type: artist
        ///        filters:
        ///        - lowercase
        ///        - [strip_nonascii, _]
        ///    title:
        ///        type: title
        ///        filters: artist
        ///
        ///config:
        ///    url: &quot;http://oldielyrics.com/lyrics/{artist}/{title}.html&quot;
        ///    pattern: [&quot;&lt;div\s+class=&quot;lyrics&quot;[^&gt;]*&gt;\s*&lt;p&gt;(?&lt;lyrics&gt;.+)&lt;/p&gt;\s*&lt;/div&gt;&quot;, s]
        ///    
        ///post-filters:
        ///- strip_html
        ///- strip_links
        ///- entity_decode
        ///- clean_spaces
        ///- utf8_encode ähnelt.
        /// </summary>
        public static string provider_oldielyrics_com {
            get {
                return ResourceManager.GetString("provider_oldielyrics_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] provider_pinkradio_com {
            get {
                object obj = ResourceManager.GetObject("provider_pinkradio_com", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die name: &quot;plyrics.com&quot;
        ///
        ///variables:
        ///    artist:
        ///        type: artist
        ///        filters:
        ///        - lowercase
        ///        - [strip_nonascii, &quot;&quot;]
        ///    title:
        ///        type: title
        ///        filters: artist
        ///
        ///config:
        ///    url: &quot;http://www.plyrics.com/lyrics/{artist}/{title}.html&quot;
        ///    pattern: [&quot;&lt;div id=\&quot;lyrics-body\&quot;&gt;(?&lt;lyrics&gt;.*?)&lt;/div&gt;&quot;, s]
        ///    
        ///post-filters:
        ///- strip_html
        ///- utf8_encode
        /// ähnelt.
        /// </summary>
        public static string provider_plyrics_com {
            get {
                return ResourceManager.GetString("provider_plyrics_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die name: &quot;rapgenius.com&quot;
        ///
        ///variables:
        ///    artist:
        ///        type: artist
        ///        filters:
        ///        - lowercase
        ///        - [strip_nonascii, -]
        ///    title:
        ///        type: title
        ///        filters: artist
        ///
        ///config:
        ///    url: &quot;http://rapgenius.com/{artist}-{title}-lyrics&quot;
        ///    pattern: [&quot;&lt;div\s+class=&quot;lyrics&quot;[^&gt;]*?&gt;(?&lt;lyrics&gt;.*?)&lt;/div&gt;&quot;, s]
        ///    
        ///post-filters:
        ///- strip_html
        ///- clean_spaces
        ///- utf8_encode ähnelt.
        /// </summary>
        public static string provider_rapgenius_com {
            get {
                return ResourceManager.GetString("provider_rapgenius_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die name: &quot;metrolyrics.com&quot;
        ///
        ///variables:
        ///    artist:
        ///        type: artist
        ///        filters:
        ///        - lowercase
        ///        - [strip_nonascii, -]
        ///    title:
        ///        type: title
        ///        filters: artist
        ///
        ///config:
        ///    url: &quot;http://www.songlyrics.com/{artist}/{title}-lyrics/&quot;
        ///    pattern: [&quot;&lt;div id=&quot;songLyricsDiv-outer&quot;&gt;(?&lt;lyrics&gt;.*?)&lt;/div&gt;&quot;, s]
        ///    
        ///post-filters:
        ///- strip_html
        ///- entity_decode
        ///- clean_spaces
        ///- utf8_encode ähnelt.
        /// </summary>
        public static string provider_songlyrics_com {
            get {
                return ResourceManager.GetString("provider_songlyrics_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die name: &quot;tekstovipjesama.com&quot;
        ///
        ///variables:
        ///    artist:
        ///        type: artist
        ///        filters:
        ///        - lowercase
        ///        - [strip_nonascii, -]
        ///    title:
        ///        type: title
        ///        filters: artist
        ///
        ///config:
        ///    url: &quot;http://tekstovipjesama.com/{artist}/{title}&quot;
        ///    pattern: [&quot;&lt;div\s+class=&quot;entry&quot;[^&gt;]*&gt;\s*&lt;div[^&gt;]*&gt;\s*(?&lt;lyrics&gt;.*?)&lt;/div&gt;&quot;, s]
        ///    
        ///post-filters:
        ///- p2break
        ///- br2nl
        ///- strip_html
        ///- entity_decode
        ///- utf8_encode ähnelt.
        /// </summary>
        public static string provider_tekstovipjesama_com {
            get {
                return ResourceManager.GetString("provider_tekstovipjesama_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die name: &quot;tekstowo.pl&quot;
        ///
        ///variables:
        ///    artist:
        ///        type: artist
        ///        filters:
        ///        - lowercase
        ///        - [strip_nonascii, _]
        ///    title:
        ///        type: title
        ///        filters: artist
        ///
        ///config:
        ///    url: &quot;http://www.tekstowo.pl/piosenka,{artist},{title}.html&quot;
        ///    pattern: [&quot;&lt;div\s+class=&quot;song-text&quot;[^&gt;]*&gt;(?&lt;lyrics&gt;.*?)&lt;p&gt;&amp;nbsp;&lt;/p&gt;&quot;, s]
        ///    
        ///post-filters:
        ///- strip_html
        ///- utf8_encode ähnelt.
        /// </summary>
        public static string provider_tekstowo_pl {
            get {
                return ResourceManager.GetString("provider_tekstowo_pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die name: &quot;teksty.org&quot;
        ///
        ///variables:
        ///    artist:
        ///        type: artist
        ///        filters:
        ///        - lowercase
        ///        - [strip_nonascii, -]
        ///    title:
        ///        type: title
        ///        filters: artist
        ///
        ///config:
        ///    url: &quot;http://teksty.org/{artist},{title},tekst-piosenki&quot;
        ///    pattern: [&quot;&lt;div\s+class=&quot;songText&quot;[^&gt;]*&gt;(?&lt;lyrics&gt;.*?)&lt;/div&gt;&quot;, s]
        ///    
        ///post-filters:
        ///- strip_html
        ///- clean_spaces
        ///- utf8_encode ähnelt.
        /// </summary>
        public static string provider_teksty_org {
            get {
                return ResourceManager.GetString("provider_teksty_org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die name: &quot;urbanlyrics.com&quot;
        ///
        ///variables:
        ///    artist:
        ///        type: artist
        ///        filters:
        ///        - lowercase
        ///        - [strip_nonascii, &quot;&quot;]
        ///    title:
        ///        type: title
        ///        filters: artist
        ///
        ///config:
        ///    url: &quot;http://www.urbanlyrics.com/lyrics/{artist}/{title}.html&quot;
        ///    pattern: [&quot;&lt;!-- start of lyrics --&gt;(?&lt;lyrics&gt;.+?)&lt;!-- end of lyrics --&gt;&quot;, s]
        ///    
        ///post-filters:
        ///- strip_html
        ///- utf8_encode ähnelt.
        /// </summary>
        public static string provider_urbanlyrics_com {
            get {
                return ResourceManager.GetString("provider_urbanlyrics_com", resourceCulture);
            }
        }
    }
}
